format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch]($style)"
style = "bright-black"
#style = "bold purple"
symbol = " "

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
#format = '([$all_status$ahead_behind]($style) )'
style = "cyan"
renamed = "»"
conflicted = "​"
untracked = "​"
#modified = "​"
#staged = "​"
#renamed = "​"
#deleted = "​"
stashed = "≡"
#ahead = "⇡"
ahead = "⇡${count}"
#behind = "⇣"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!"
staged = "+"
deleted = "✘"
#style = "bold red"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv$symbol]($style) "
style = "bright-black"
symbol = " "

[golang]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[haskell]
symbol = " "
